# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20170317_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'permissions': (('NS', 'Use Plan at NetSuite'),)},
        ),
    ]
