# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('plans', '0002_auto_20170303_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
