# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20170317_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='groups',
        ),
    ]
