# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_remove_plan_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'permissions': (('view_plan', 'View Plan'),)},
        ),
    ]
