# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_auto_20170317_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
