# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 19:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FilePathField(default='', match='.*\\.(log|ini|xml|yml|zip)')),
                ('success', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('D', 'Documentation'), ('S', 'Scan')], default='D', max_length=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniform_resource_locator', models.URLField(help_text='Please use the following format: http(s)://...!', max_length=2083)),
                ('team_id', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1)])),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scans.Scan')),
                ('name', models.CharField(default='', max_length=256)),
                ('uploaded_to', models.FilePathField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='metafile',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.Scan'),
        ),
        migrations.AddField(
            model_name='metafile',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scans.Zip'),
        ),
    ]
