# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 18:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FilePathField(default='', match='.*\\.(log|json|ini|xml|yml|zip|w3af|afr)')),
                ('role', models.CharField(choices=[('D', 'Documentation'), ('S', 'Scan')], default='D', max_length=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniform_resource_locator', models.URLField(help_text='Please use the following format: http(s)://', max_length=2083)),
                ('application_id', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(10)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('success', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, default='', max_length=256)),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(blank=True, default='', max_length=256)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scans.Scan')),
                ('name', models.CharField(default='', max_length=256)),
                ('uploaded_to', models.FilePathField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='scan',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='metafile',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.Scan'),
        ),
        migrations.AddField(
            model_name='metafile',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scans.Tool'),
        ),
        migrations.AlterUniqueTogether(
            name='scan',
            unique_together=set([('user_profile', 'id')]),
        ),
        migrations.AddField(
            model_name='metafile',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.Zip'),
        ),
    ]
