# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassFailTool',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scans.Tool')),
                ('test', models.NullBooleanField()),
            ],
            bases=('scans.tool',),
        ),
    ]
