# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_passfailtool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='task_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
