# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_auto_20170404_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='arguments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
