# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 22:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_auto_20161020_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='team_id',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='scan',
            name='uniform_resource_locator',
            field=models.URLField(help_text='Please use the following format: http(s)://', max_length=2083),
        ),
    ]
