# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_tool_arguments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='arguments',
            new_name='configuration',
        ),
    ]
