# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_auto_20161020_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metafile',
            name='report',
            field=models.FilePathField(default='', match='.*\\.(log|ini|xml|yml|zip|w3af|afr)'),
        ),
    ]
