# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_auto_20161025_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='team_id',
            new_name='application_id',
        ),
    ]
