# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20170328_1251'),
        ('scans', '0005_auto_20170719_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='plans',
        ),
        migrations.AddField(
            model_name='tool',
            name='plans',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plans.Plan'),
            preserve_default=False,
        ),
    ]
