# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20170328_1251'),
        ('scans', '0006_auto_20170719_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='plans',
        ),
        migrations.AddField(
            model_name='tool',
            name='plans',
            field=models.ManyToManyField(to='plans.Plan'),
        ),
    ]
