# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0007_metafile_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, default='', max_length=256)),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('work_directory', models.FilePathField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.Scan')),
            ],
        ),
        migrations.AlterField(
            model_name='metafile',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.Tool'),
        ),
    ]
