# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0008_auto_20161117_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metafile',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scans.Tool'),
        ),
    ]
