# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('scans', '0010_scan_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='user_profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
            preserve_default=False,
        ),
    ]
