# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0014_plan_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metafile',
            name='success',
        ),
        migrations.AddField(
            model_name='scan',
            name='summary',
            field=models.FilePathField(default='', match='.*\\.json'),
        ),
        migrations.AlterField(
            model_name='metafile',
            name='report',
            field=models.FilePathField(default='', match='.*\\.(log|json|ini|xml|yml|zip|w3af|afr)'),
        ),
    ]
