# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0015_auto_20170206_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='task_id',
        ),
        migrations.AddField(
            model_name='scan',
            name='success',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='tool',
            name='state',
            field=models.PositiveIntegerField(choices=[(0, 'PENDING'), (1, 'SUCCESS'), (2, 'FAILURE')], default=0),
        ),
    ]
