# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0016_auto_20170209_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='state',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
