# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0004_auto_20161025_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniform_resource_locator', models.URLField(max_length=2083)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'DONE'), (2, 'FAILED'), (3, 'IDLE'), (4, 'PARTIAL FAILURE')], default=3)),
                ('scan', models.ManyToManyField(to='scans.Scan')),
            ],
        ),
    ]
