# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('uniform_resource_locator', models.URLField(max_length=2083)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.Scan')),
            ],
        ),
    ]
