# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20161213_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='status',
        ),
    ]
